/* header guard generated by genheader.pl */
#ifndef _cscript_executor_h_
#define _cscript_executor_h_

#define VAR_STR 's'
#define VAR_INT 'i'
#define VAR_FLT 'f'
#define VAR_FUN 'F'
#define VAR_ARY 'a'
#define VAR_HSH 'h' /* TODO: Hash table */
#define VAR_GLB 'g' /* TODO: Typeglob */

struct cs_var {
	int nodetype;
	int type;
	void *var;
};

int treeresolve(struct cse_tree *tree);
int treeexec(struct cse_tree *tree);



#endif /* _cscript_executor_h_ */
