/* header guard generated by genheader.pl */
#ifndef _cscript_htbl_h_
#define _cscript_htbl_h_

struct cscript_htbl_node;

struct cscript_htbl {
	int hash_size;
	struct cscript_htbl_node** nodes;
	long (*hash_func)(const char *str, int size);
	void (*free_func)(void *);
};

struct cscript_htbl_node {
	char *k;
	void *v;
};

struct cscript_htbl*
cscript_htbl_new(int hash_size, /* required: hash table size */
		 long (*hash_function)(const char *, int), /* optional */
		 void (*free_function)(void *)
	);



int /* returns 0 if successed, else -1 */
cscript_htbl_add(struct cscript_htbl *htbl, const char *k, void *v);
void
cscript_htbl_del(struct cscript_htbl *htbl, const char *k);

int /* -1: failed, 0: successed */
cscript_htbl_find(const struct cscript_htbl *htbl, const char *k, void **v);


void
cscript_htbl_free(struct cscript_htbl *htbl);



#endif /* _cscript_htbl_h_ */
