/* header guard generated by genheader.pl */
#ifndef _cscript_runstack_h_
#define _cscript_runstack_h_

typedef void free_function(void *value);

struct cs_rs {
	int type;
	char *name;
	struct cs_rs *parent;
	free_function *free_handler;
	void *symbol_table;
};

struct cs_rs *
cscript_runstack_new(int type, const char *name,
		     struct cs_rs *parent, free_function *free_handler);

void
cscript_runstack_free(struct cs_rs * rs);


void
cscript_runstack_put(struct cs_rs *rs, const char *name, void *value);
void
cscript_runstack_put_static(struct cs_rs *rs, const char *name, void *value);

void
cscript_runstack_delete(struct cs_rs *rs, const char *name);
int
cscript_runstack_find(struct cs_rs *rs, const char *name, void **outvalue);

int
cscript_runstack_find_local(struct cs_rs *rs,
			    const char *name, void **outvalue);

int
cscript_runstack_count_local(struct cs_rs *rs);

struct cs_rs *
cscript_runstack_global(struct cs_rs *rs);



#endif /* _cscript_runstack_h_ */
