/* header guard generated by genheader.pl */
#ifndef _cscript_parser_h_
#define _cscript_parser_h_

/* structure declaratioins */
struct cs_bt;
struct cs_int;
struct cs_flt;
struct cs_str;
struct cs_tok;
struct cs_asgn;
struct cs_bin;
struct cs_unary;
struct cs_tern;
struct cs_symlst;
struct cs_explst;
struct cs_if;
struct cs_while;
struct cs_list;
struct cs_hash;
struct cs_stmt;
struct cs_block;
struct cs_code;

/* structure definitions */
struct cs_bt {		/* basic binary tree */
	int nodetype;
	struct cs_bt *l, *r;
};

struct cs_int {		/* int value */
	int nodetype; /* i */
	long val;
};

struct cs_flt {		/* float value */
	int nodetype; /* f */
	double val;
};

struct cs_str {		/* string value */
	int nodetype; /* s */
	char *str;
};

struct cs_tok {		/* token name */
	int nodetype; /* t */
	char *name;
};

struct cs_asgn {
	int nodetype; /* = */
	struct cs_tok* lhs;
	struct cs_bt* rhs;
};

/* arithmetic binary operation */
#define CS_BIN_PLU 1
#define CS_BIN_MIN 2
#define CS_BIN_MUL 3
#define CS_BIN_DIV 4
/* bitwise binary operation */
#define CS_BIN_BAND 5
#define CS_BIN_BOR  6
#define CS_BIN_BXOR 7
/* logical binary operation */
#define CS_BIN_LAND 8
#define CS_BIN_LOR  9
/* equality operation */
#define CS_BIN_EQ  10
#define CS_BIN_NE  11
/* retional operation */
#define CS_BIN_LT  12
#define CS_BIN_GT  13
#define CS_BIN_LE  14
#define CS_BIN_GE  15

struct cs_bin {		/* binary operation */
	int nodetype; /* + */
	int type;
	struct cs_bt* lhs;
	struct cs_bt* rhs;
};

#define CS_UN_PLU 1
#define CS_UN_MIN 2
#define CS_UN_NOT 3
#define CS_UN_REV 4
#define CS_UN_INC_PRE 5
#define CS_UN_INC_PST 6
#define CS_UN_DEC_PRE 7
#define CS_UN_DEC_PST 8

struct cs_unary {	/* unary operation */
	int nodetype; /* - */
	int type;
	struct cs_bt *operand;
};

#define CS_TERN_COND 1	/* ?: operator */
struct cs_tern {	/* ternary operation */
	int nodetype; /* ? */
	int type;
	struct cs_bt *op1, *op2, *op3;
};


struct cs_symlst {	/* symbol list */
	int nodetype; /* a */
	struct cs_tok *name;
	struct cs_symlst *next;
};

struct cs_explst {	/* expression list */
	int nodetype; /* e */
	struct cs_bin *item;
	struct cs_explst *next;
};

struct cs_if {		/* if statment */
	int nodetype; /* I */
	struct cs_bt *cond;
	struct cs_stmt *if_part;
	struct cs_stmt *else_part;
};

#define CS_DO_WHILE 1
#define CS_WHILE    2
strct cs_while {
	int nodetype; /* W */
	int mode;
	struct cs_bin *cond;
	struct cs_stmt *loop;
};

struct cs_list { /* list */
	int nodetype; /* l */
	struct cs_explst *content;
};

struct cs_hash {
	int nodetype; /* h */
	/* TODO */
};

struct cs_stmt {	/* statement */
	int nodetype; /* S */
	struct cs_bin *stmt;
};

struct cs_block {
	int nodetype; /* B */
	struct cs_code *code;
};

struct cs_code {	/* statement list */
	int nodetype; /* C */
	struct cs_stmt *stmt;
	struct cs_code *next;
};

/* binary tree construction functions */
struct cs_bt *
mkbt(int nodetype, struct cs_bt *l, struct cs_bt *r);
struct cs_bt *
mkint(long val);
struct cs_bt *
mkflt(double val);
struct cs_bt *
mkstr(char *str);
struct cs_bt *
mktok(char *name);
struct cs_bt *
mkasgn(int assignment, struct cs_bt *lhs, struct cs_bt *rhs);
struct cs_bt *
mkbin(int type, struct cs_bt *lhs, struct cs_bt *rhs);
struct cs_bt *
mkunary(int type, struct cs_bt *operand);
struct cs_bt *
mktern(int type, struct cs_bt *op1, struct cs_bt *op2, struct cs_bt *op3);
struct cs_bt *
mksymlst(struct cs_bt *lst, struct cs_bt *newitem);
struct cs_bt *
mkexplst(struct cs_bt *lst, struct cs_bt *newitem);
struct cs_bt *
mkif(struct cs_bt *cond, struct cs_bt *if_part, struct cs_bt *else_part);
struct cs_bt *
mkwhile(int mode, struct cs_bt* cond, struct cs_bt *loop_part);
struct cs_bt *
mklist(struct cs_bt *exp_list);
struct cs_bt *
mkhash(void); /* INCOMPLETED */
struct cs_bt *
mkstmt(struct cs_bt *exp);
struct cs_bt *
mkblock(struct cs_bt *code_block);
struct cs_bt *
mkcode(struct cs_bt *code, struct cs_bt *nextstmt);

/**/

#endif /* _cscript_parser_h_ */
