/* header guard generated by genheader.pl */
#ifndef _cscript_executor_h_
#define _cscript_executor_h_

struct cs_var {
	int nodetype;
	int type;
	void *var;
};

int treeresolve(struct cse_tree *tree);
int treeexec(struct cse_tree *tree);



#endif /* _cscript_executor_h_ */
