/* header guard generated by genheader.pl */
#ifndef _cscript_parser_h_
#define _cscript_parser_h_

/* structure declaratioins */
struct cs_bt;
struct cs_int;
struct cs_flt;
struct cs_str;
struct cs_tok;
struct cs_asgn;
struct cs_bin;
struct cs_unary;
struct cs_tern;
struct cs_symlst;
struct cs_explst;
struct cs_if;
struct cs_while;
struct cs_for;
struct cs_forin;
struct cs_list;
struct cs_hash;
struct cs_stmt;
struct cs_block;
struct cs_code;

/* structure definitions */
struct cs_bt {		/* basic binary tree */
	int nodetype;
	struct cs_bt *l, *r;
};

struct cs_int {		/* int value */
	int nodetype; /* i */
	long val;
};

struct cs_flt {		/* float value */
	int nodetype; /* f */
	double val;
};

struct cs_str {		/* string value */
	int nodetype; /* s */
	char *str;
};

struct cs_tok {		/* token name */
	int nodetype; /* t */
	char *name;
};

struct cs_asgn {
	int nodetype; /* = */
	struct cs_tok* lhs;
	struct cs_bt* rhs;
};

/* arithmetic binary operation */
#define CS_BIN_PLU '+'
#define CS_BIN_MIN '-'
#define CS_BIN_MUL '*'
#define CS_BIN_DIV '/'
/* bitwise binary operation */
#define CS_BIN_BAND '&'
#define CS_BIN_BOR  '|'
#define CS_BIN_BXOR '^'
#define CS_BIN_LSHFT 'l'
#define CS_BIN_RSHFT 'r'
/* logical binary operation */
#define CS_BIN_LAND 'A'
#define CS_BIN_LOR  'O'
/* equality operation */
#define CS_BIN_EQ  '='
#define CS_BIN_NE  '!'
/* retional operation */
#define CS_BIN_LT  '<'
#define CS_BIN_GT  '>'
#define CS_BIN_LE  'L'
#define CS_BIN_GE  'G'

struct cs_bin {		/* binary operation */
	int nodetype; /* + */
	int type;
	struct cs_bt* lhs;
	struct cs_bt* rhs;
};

#define CS_UN_PLU '+'
#define CS_UN_MIN '-'
#define CS_UN_NOT '!'
#define CS_UN_REV '~'
#define CS_UN_INC_PRE 'i'
#define CS_UN_INC_PST 'I'
#define CS_UN_DEC_PRE 'd'
#define CS_UN_DEC_PST 'D'

struct cs_unary {	/* unary operation */
	int nodetype; /* - */
	int type;
	struct cs_bt *operand;
};

#define CS_TERN_COND '?'	/* ?: operator */
struct cs_tern {	/* ternary operation */
	int nodetype; /* ? */
	int type;
	struct cs_bt *op1, *op2, *op3;
};


struct cs_symlst {	/* symbol list */
	int nodetype; /* a */
	struct cs_tok *name;
	struct cs_symlst *next;
};

struct cs_explst {	/* expression list */
	int nodetype; /* e */
	struct cs_bin *item;
	struct cs_explst *next;
};

struct cs_if {		/* if statment */
	int nodetype; /* I */
	struct cs_bt *cond;
	struct cs_stmt *if_part;
	struct cs_stmt *else_part;
};

#define CS_DO_WHILE 1
#define CS_WHILE    2
struct cs_while {
	int nodetype; /* W */
	int mode;
	struct cs_bt *cond;
	struct cs_stmt *loop;
};

struct cs_for {
	int nodetype; /* F */
	struct cs_stmt *start, *end;
	struct cs_bt *cond;
	struct cs_stmt *loop;
};

struct cs_forin {
	int nodetype; /* Q */
	struct cs_tok *name;
	struct cs_bt *list;
	struct cs_stmt *loop;
};

struct cs_list { /* list */
	int nodetype; /* l */
	struct cs_explst *content;
};

struct cs_hash {
	int nodetype; /* h */
	/* TODO */
};

struct cs_stmt {	/* statement */
	int nodetype; /* S */
	struct cs_bin *stmt;
};

struct cs_block {
	int nodetype; /* B */
	struct cs_code *code;
};

struct cs_code {	/* statement list */
	int nodetype; /* C */
	struct cs_stmt *stmt;
	struct cs_code *next;
};

struct cs_fcall {
	int nodetype; /* c */
	struct cs_bt *func;
	struct cs_explst *arg;
};

/* binary tree construction functions */
struct cs_bt *
mkbt(int nodetype, struct cs_bt *l, struct cs_bt *r);
struct cs_bt *
mkint(long val);
struct cs_bt *
mkflt(double val);
struct cs_bt *
mkstr(char *str);
struct cs_bt *
mktok(char *name);
struct cs_bt *
mkasgn(int assignment, struct cs_bt *lhs, struct cs_bt *rhs);
struct cs_bt *
mkbin(int type, struct cs_bt *lhs, struct cs_bt *rhs);
struct cs_bt *
mkunary(int type, struct cs_bt *operand);
struct cs_bt *
mktern(int type, struct cs_bt *op1, struct cs_bt *op2, struct cs_bt *op3);
struct cs_bt *
mksymlst(struct cs_bt *lst, struct cs_bt *newitem);
struct cs_bt *
mkexplst(struct cs_bt *lst, struct cs_bt *newitem);
struct cs_bt *
mkif(struct cs_bt *cond, struct cs_bt *if_part, struct cs_bt *else_part);
struct cs_bt *
mkunless(struct cs_bt *cond, struct cs_bt *unless_part, struct cs_bt*else_part);
struct cs_bt *
mkwhile(int mode, struct cs_bt* cond, struct cs_bt *loop_part);
struct cs_bt *
mkfor(struct cs_bt *start, struct cs_bt *cond,
      struct cs_bt *end, struct cs_bt *loop);
struct cs_bt *
mkforin(struct cs_bt *var, struct cs_bt *list, struct cs_bt *loop);
struct cs_bt *
mklist(struct cs_bt *exp_list);
struct cs_bt *
mkhash(void); /* INCOMPLETED */
struct cs_bt *
mkstmt(struct cs_bt *exp);
struct cs_bt *
mkblock(struct cs_bt *code_block);
struct cs_bt *
mkcode(struct cs_bt *code, struct cs_bt *nextstmt);
struct cs_bt *
mkfcall(struct cs_bt *func, struct cs_bt *args);

/* deallocate functions */
void
free_tree(struct cs_bt *tree);


/* debug interface */
void
print_tree(struct cs_bt *tree);

#endif /* _cscript_parser_h_ */
