/* header guard generated by genheader.pl */
#ifndef _cscript_dtl_h_
#define _cscript_dtl_h_

/* dynamic type library */

struct cscript_str {
	int type;
	char *s;
	int len;
};

struct cscript_list_node {
	int type;
	void *val;
	struct cscript_list_node *next;
};
struct cscript_list {
	int len;
	struct cscript_list_node *head;
};

struct cscript_hash_node {
	int type;
	void *val;
	struct script_hash_node *next;
};
struct cscript_hash {
	int keytype;
	int size;
	struct cscript_hash_node *nodes;
};


struct cscript_str *
cscript_str_new(void);
struct cscript_str *
cscript_str_new_str(const char *s);
struct cscript_str *
cscript_str_new_nstr(char *s, int len);

int
cscript_str_len(const struct cscript_str *s);

struct cscript_str *
cscript_str_dup(const struct cscript_str *s);

struct cscript_str *
cscript_str_copy(struct cscript_str *dst, const struct cscript_str *src);

void
cscript_str_free(struct cscript_str *s);

const char *
cscript_str_c_str(const struct cscript_str *s);

char *
cscript_str_c_str_dup(const struct cscript_str *s);


/* list function */
struct cscript_list *
cscript_list_new(void);

struct cscript_list *
cscript_list_append(struct cscript_list *list, int type, void *val);
struct cscript_list *
cscript_list_prepend(struct cscript_list *list, int type, void *val);
struct cscript_list *
cscript_list_insert(struct cscript_list *list, int pos, int type, void *val);

struct cscript_list *
cscript_list_extend(struct cscript_list *list,
		    const struct cscript_list *list_to_extend);

struct cscript_list *
cscript_list_slice(const struct cscript_list *list, int start, int end);

struct cscript_list *
cscript_list_get(struct cscript_list *list, int pos,
		 int *rettype, void **retval);

int
cscript_list_len(const struct cscript_list *list);

void
cscript_list_free(struct cscript_list *list);



/* hash table function */


#endif /* _cscript_dtl_h_ */
