/* header guard generated by genheader.pl */
#ifndef _cscript_runtime_h_
#define _cscript_runtime_h_

struct cscript_htbl;

struct cscript_runstack {
	char *name;
	cscript_htbl *symtbl; /* symbol table */
	struct cscript_runstack *parent;
};


struct cscript_runstack *
cscript_runstack_new(struct cscript_runstack *parent, const char *name);
void
cscript_runstack_free(struct cscript_runstack *runstack);

void
cscript_runstack_add(struct cscript_runstack *runstack,
		     const char *symname, void *value);
void
cscript_runstack_del(struct cscript_runstack *runstack, const char *symname);


int
cscript_runstack_find(struct cscript_runstack *runstack,
		      const char *name, void **value);
int
cscript_runstack_find_no_parent(struct cscript_runstack *runstack,
				const char *name, void **value);

struct cscript_runstack *
cscript_runstack_global(struct cscript_runstack *runstack);



#endif /* _cscript_runtime_h_ */
