/* header guard generated by genheader.pl */
#ifndef _cscript_parser_h_
#define _cscript_parser_h_

#include <stdio.h>

struct csp_err {
	int no;
	char *msg;
};

struct csp_node;
union _csp_vtype_tag {
	struct csp_node *op1;
	struct {
		struct csp_node *op1;
		struct csp_node *op2;
	} v2;
	struct {
		struct csp_node *op1;
		struct csp_node *op2;
		struct csp_node *op3;
	} v3;
	struct {
		struct csp_node *op1;
		struct csp_node *op2;
		struct csp_node *op3;
		struct csp_node *op4;
	} v4;
};

struct csp_node {
	int type;
	unsigned long flags;
	struct csp_node *next;
	union _csp_vtype_tag v;
};

int
cscript_parse_source(FILE *f, struct csp_node **tree, struct csp_err *err);

int                              /* output           output    */
cscript_save(struct csp_node *tree, char **bytecode, int *len);
int                                /* output                  */
cscript_load(char *bytecode, int len, struct csp_node **tree);


extern void
cscript_parser_init(void);

extern void
cscript_emit0(int type),
cscript_emit1(int type, void *a1),
cscript_emit2(int type, void *a1, void *a2),
cscript_emit3(int type, void *a1, void *a2, void *a3);


#endif /* _cscript_parser_h_ */
