/* header guard generated by genheader.pl */
#ifndef _cscript_btree_h_
#define _cscript_btree_h_

struct _cs_bt_node;
struct cs_bt {
	void (*free_handler)(void *);
	struct _cs_bt_node *tree;
};


struct cs_bt *
cscript_btree_new(void (*free_handler)(void *));

void
cscript_btree_free(struct cs_bt *tree);

void
cscript_btree_insert(struct cs_bt *tree, const char *name, void *value);

int
cscript_btree_delete(struct cs_bt *tree, const char *name);

int
cscript_btree_find(struct cs_bt *tree, const char *name, void **outvalue);



#endif /* _cscript_btree_h_ */
