/* header guard generated by genheader.pl */
#ifndef _cscript_common_h_
#define _cscript_common_h_

#include <stdio.h>

/* error/warning/log */
extern FILE* cscript_outfile;

void cscript_init_logfile(char *filename);
void cscript_error(char *s, ...);
void cscript_warning(char *s, ...);
void cscript_log(char *s, ...);

#endif /* _cscript_common_h_ */
